### ISSUE TITLE
HTML  作业

### ISSUE THREAD

**Issue by doudou1212** [ooxiaoyan/ThoughtWorks_baby#1]
[[homework](url) link](https://github.com/ooxiaoyan/ThoughtWorks_baby/blob/master/ThoughtWorks_2018_01_06/html/html.html)

👍 
1. h1 标签只出现了一次
2. 知道inline element 与block element的区别 （例如： span, div）
3. 将每一个大题分成了一个块

To be imporved:
1. 在每一个大题中，可以利用ol的特性实现小题中的序号：
```html
<ol>
<li>UML与软件工程的关系是:</li>
<li>Java语言支持:</li>
</ol>
```

2.有一些不必要的标签，这些标签删除也不会影响页面效果，如：[div](https://github.com/ooxiaoyan/ThoughtWorks_baby/blob/master/ThoughtWorks_2018_01_06/html/html.html#L39)

**Comment by ooxiaoyan** [comment]
have already been solved
