### ISSUE TITLE
CSS homework

### ISSUE THREAD

**Issue by doudou1212** [ooxiaoyan/ThoughtWorks_baby#2]
[homework link](https://github.com/ooxiaoyan/ThoughtWorks_baby/blob/master/ThoughtWorks_2018_01_06/html%2Bcss/css/style.css)

👍 
1. html与css分开两个文件，将css link到html中
2. 没有使用id。一般css尽量用class，尽可能不用id
3. 为每一个class设计不同的样式，可以将多个class组合起来为不同的element生成样式，如```<div class="b title4">   <div class="box box_in">```

To be improved:
1. CSS 中body没有样式，可以删掉
2. 一些class的起名不是很好，如： b，看到b这个名字也想不出来这个class的作用；checkbox， 很容易联想这是为了checkbox加的一些样式，但其实与checkbox无关
3. input标签需要闭合

**Comment by ooxiaoyan** [comment]
have already been solved
